imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.factory
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../web/themes": theme
        "%kernel.root_dir%/../" : root

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        wrapper_class: Topxia\Service\Common\Connection
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum:       string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    topxia.twig.web_extension:
        class: AppBundle\Twig\Extension\WebExtension
        arguments:    ['@service_container']
        tags:
            - { name: twig.extension }

    session.handler.pdo.connection:
        class: PDO
        calls:
            - [setAttribute, [3, 2]]

        arguments:
            dsn:      "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            user:     %database_user%
            password: %database_password%

    session.handler.pdo:
        class:     AppBundle\Handler\UserPdoSessionHandler
        arguments: ['@session.handler.pdo.connection', '%session.handler.pdo.options%', '@security.context', '@service_container']

    session.handler.factory:
        class: SessionHandlerInterface
        factory_class: Topxia\Service\Common\SessionHandlerFactory
        factory_method: getSessionHandler
        arguments:
            - "@service_container"

    topxia.twig.html_extension:
        class: Topxia\WebBundle\Twig\Extension\HtmlExtension
        tags:
            - { name: twig.extension }

    topxia.twig.menu_extension:
        class: Topxia\WebBundle\Twig\Extension\MenuExtension
        arguments:    ['@service_container']
        tags:
            - { name: twig.extension }

    kernel.listener.kernel_request_listener:
        class: Topxia\WebBundle\Listener\KernelRequestListener
        arguments:    ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority:255 }

    kernel.listener.ajax_exception_listener:
        class: Topxia\WebBundle\Listener\AjaxExceptionListener
        arguments:    ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority:255 }

parameters:
    session.handler.pdo.options:
         db_table:    sessions
         db_id_col:   sess_id
         db_data_col: sess_data
         db_time_col: sess_time
         db_lifetime_col: sess_lifetime
         db_user_id_col: sess_user_id
    topxia.upload.public_directory: "%kernel.root_dir%/../web/files"
    topxia.upload.public_url_path: "/files"
    topxia.upload.private_directory: "%kernel.root_dir%/data/private_files"
